[profile.default]
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"
cbor_metadata = false
optimize = true
optimizer_runs = 200
via-ir = false
runs = 200

[profile.deploy]
via-ir = true

[profile.default.release]
version = "0.8.25"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fuzz]
runs = 256
