# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  cbor_metadata = false
  evm_version = "paris"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 100_000
  out = "out"
  script = "script"
  solc = "0.8.23"
  src = "src"
  test = "test"
  remappings = [
    "@account-abstraction/=node_modules/account-abstraction/contracts/",
    "@openzeppelin/=node_modules/@openzeppelin/contracts/",
    "erc7579-implementation/=node_modules/erc7579-implementation/src/",
    "sentinellist/=node_modules/@rhinestone/sentinellist/src/",
    "forge-std/=/home/elli/Documents/plentifi/clean/contracts/lib/forge-std/src/",
    "solady/=/home/elli/Documents/plentifi/clean/contracts/lib/solady/src/",
    "ds-test/=/home/elli/Documents/plentifi/clean/contracts/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=/home/elli/Documents/plentifi/clean/contracts/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "src/=src/"
  ]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  # sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  # sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
